apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database/secret.yaml
  - database/persistent-volume-claim.yaml
  - database/deployment.yaml
  - database/service.yaml
  - blog/config-map.yaml
  - blog/deployment.yaml
  - blog/service.yaml
  - blog/route.yaml
  - blog/horizontal-pod-autoscaler.yaml
