kind: Secret
apiVersion: v1
metadata:
  name: blog-db
  labels:
    app: blog-db
    app.kubernetes.io/component: blog-db
    app.kubernetes.io/instance: blog-db
    template: postgresql-persistent-template
stringData:
  database-name: blogdb
  database-password: blogdb
  database-user: blogdb
  database-url: postgresql://blogdb:blogdb@blog-db:5432/blogdb
type: Opaque
