kind: Service
apiVersion: v1
metadata:
  name: blog-app
  labels:
    app: blog-app
    app.kubernetes.io/component: blog-app
    app.kubernetes.io/instance: blog-app
    app.kubernetes.io/name: python
    app.kubernetes.io/part-of: blog-app
    app.openshift.io/runtime: python
    app.openshift.io/runtime-version: 3.8-ubi7
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: blog-app
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}
